apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: nkn3pn.dok7yzw9ma9hfdnn
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 2400:8500:2002:3318:163:44:115:241
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: cnh-01
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
failSwapOn: false
eventRecordQPS: 4
kubeReserved:
  memory: "100Mi"
  cpu: "50m"
systemReserved:
  memory: "150Mi"
  cpu: "50m"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.36.0
apiServer:
  extraArgs:
    max-requests-inflight: "40"
    max-mutating-requests-inflight: "20"
    audit-log-maxsize: "10"
    audit-log-maxbackup: "1"
    enable-priority-and-fairness: "false"
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "500m"
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: 163.44.115.241:6443
controllerManager:
  extraArgs:
    node-cidr-mask-size-ipv4: "26"
    node-cidr-mask-size-ipv6: "122"
  resources:
    requests:
      memory: "80Mi"
      cpu: "50m"
    limits:
      memory: "150Mi"
      cpu: "200m"
dns: {}
encryptionAlgorithm: RSA-2048
etcd:
  external:
    endpoints:
    - https://127.0.0.1:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
imageRepository: registry.k8s.io
networking:
  dnsDomain: cluster.local
  podSubnet: fd00:10:244::/108,10.244.0.0/16
  serviceSubnet: fd00:10:96::/108,10.96.0.0/12
proxy: {}
scheduler: {}
